# WHEN NATURE STRIKES
## Exploratory Data Analysis of Natural Disasters

### Project Objective
To analyse global natural disaster data from EM-DAT
and investigate whether the most frequent disaster
types are also the most destructive.

### Analysis Areas
1. Disaster frequency by type
2. Human impact analysis
3. Economic damage analysis
4. Yearly and decadal trends
5. Frequency versus destructiveness

### Dataset
EM-DAT Natural Disaster Records (1900–2026)

### Data Source
EM-DAT - CRED / UCLouvain

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import os

# Visualization settings
sns.set_theme(style="whitegrid")
plt.rcParams["figure.figsize"] = (12, 6)

print("All libraries imported successfully!")

All libraries imported successfully!

In [2]:
# Load processed datasets

events = pd.read_csv(
    "../data/processed/natural_disaster_events.csv",
    encoding="utf-8-sig"
)

type_summary = pd.read_csv(
    "../data/processed/natural_disaster_type_summary.csv",
    encoding="utf-8-sig"
)

print("Datasets loaded successfully!")

Datasets loaded successfully!

In [3]:
print("EVENT-LEVEL DATASET")
print("Rows:", events.shape[0])
print("Columns:", events.shape[1])

print("\nDISASTER TYPE SUMMARY")
print("Rows:", type_summary.shape[0])
print("Columns:", type_summary.shape[1])

EVENT-LEVEL DATASET
Rows: 15727
Columns: 35

DISASTER TYPE SUMMARY
Rows: 15
Columns: 19

In [6]:
display(events.head())
display(type_summary.head())

,Event ID,Disaster Group,Disaster Subgroup,Disaster Type,Disaster Subtype,Classification Key,Start Year,Start Month,Start Day,Start Date,...,No. Homeless,No. Homeless Reported Country Impacts,Total Affected,Total Affected Reported Country Impacts,"Total Damage, Adjusted ('000 US$)","Total Damage, Adjusted ('000 US$) Reported Country Impacts","Total Damage, Adjusted (million US$)","Total Damage, Adjusted (million US$) Reported Country Impacts",Magnitude,Magnitude Reported Country Impacts
0,1987-0326,Natural,Hydrological,Flood,Riverine flood,nat-hyd-flo-riv,1987,10.0,31.0,1987-10-31,...,NaN,0,26000.0,1,87835.0,1,87.835,1,NaN,0
1,1987-0590,Natural,Meteorological,Storm,Tropical cyclone,nat-met-sto-tro,1987,11.0,21.0,1987-11-21,...,200.0,1,203.0,1,17000.0,1,17.000,1,148.0,1
2,1988-0312,Natural,Meteorological,Storm,Tropical cyclone,nat-met-sto-tro,1988,7.0,16.0,1988-07-16,...,21235.0,1,117508.0,2,766391.0,2,766.391,2,430.0,2
3,1988-0424,Natural,Meteorological,Storm,Tropical cyclone,nat-met-sto-tro,1988,8.0,11.0,1988-08-11,...,NaN,0,870000.0,1,251236.0,2,251.236,2,740.0,4
4,1989-0447,Natural,Meteorological,Storm,Tropical cyclone,nat-met-sto-tro,1989,6.0,24.0,1989-06-24,...,NaN,0,NaN,0,1298506.0,1,1298.506,1,85.0,1

,Disaster Group,Disaster Type,Unique Events,Total Deaths,Total Deaths Events with Reported Values,No. Injured,No. Injured Events with Reported Values,No. Affected,No. Affected Events with Reported Values,No. Homeless,No. Homeless Events with Reported Values,Total Affected,Total Affected Events with Reported Values,"Total Damage, Adjusted ('000 US$)","Total Damage, Adjusted ('000 US$) Events with Reported Values","Total Damage, Adjusted (million US$)","Total Damage, Adjusted (million US$) Events with Reported Values",Magnitude,Magnitude Events with Reported Values
0,Natural,Animal incident,1,12.0,1,NaN,0,5.000000e+00,1,NaN,0,5.000000e+00,1,NaN,0,NaN,0,NaN,0
1,Natural,Drought,647,11734353.0,67,32.0,1,3.028711e+09,477,20000.0,1,3.028731e+09,477,4.568840e+08,205,456883.972,205,2919218.00,47
2,Natural,Earthquake,1573,2440922.0,1190,2982082.0,1087,2.261647e+08,880,25711622.0,482,2.548584e+08,1325,1.803517e+09,626,1803517.195,626,10004.62,1488
3,Natural,Epidemic,1447,9629942.0,1243,3530472.0,188,4.733362e+07,1083,NaN,0,5.086409e+07,1257,6.100000e+01,1,0.061,1,27038779.00,24
4,Natural,Extreme temperature,433,397964.0,364,2149675.0,98,1.390115e+08,105,255587.0,4,1.414168e+08,181,1.434658e+08,60,143465.781,60,5607.20,237

In [7]:
print("EVENT DATASET COLUMNS:")
for column in events.columns:
    print(column)

print("\nTYPE SUMMARY COLUMNS:")
for column in type_summary.columns:
    print(column)

EVENT DATASET COLUMNS:
Event ID
Disaster Group
Disaster Subgroup
Disaster Type
Disaster Subtype
Classification Key
Start Year
Start Month
Start Day
Start Date
End Year
End Month
End Day
End Date
Decade
Country Count
Countries
ISO Codes
Country Impact Records
Total Deaths
Total Deaths Reported Country Impacts
No. Injured
No. Injured Reported Country Impacts
No. Affected
No. Affected Reported Country Impacts
No. Homeless
No. Homeless Reported Country Impacts
Total Affected
Total Affected Reported Country Impacts
Total Damage, Adjusted ('000 US$)
Total Damage, Adjusted ('000 US$) Reported Country Impacts
Total Damage, Adjusted (million US$)
Total Damage, Adjusted (million US$) Reported Country Impacts
Magnitude
Magnitude Reported Country Impacts

TYPE SUMMARY COLUMNS:
Disaster Group
Disaster Type
Unique Events
Total Deaths
Total Deaths Events with Reported Values
No. Injured
No. Injured Events with Reported Values
No. Affected
No. Affected Events with Reported Values
No. Homeless
No. Homeless Events with Reported Values
Total Affected
Total Affected Events with Reported Values
Total Damage, Adjusted ('000 US$)
Total Damage, Adjusted ('000 US$) Events with Reported Values
Total Damage, Adjusted (million US$)
Total Damage, Adjusted (million US$) Events with Reported Values
Magnitude
Magnitude Events with Reported Values

In [8]:
#CHECK DUPLICATE EVENT IDs

In [9]:
print("Total records:", len(events))

print(
    "Unique Event IDs:",
    events["Event ID"].nunique()
)

print(
    "Duplicate Event IDs:",
    events["Event ID"].duplicated().sum()
)

Total records: 15727
Unique Event IDs: 15727
Duplicate Event IDs: 0

In [10]:
#CHECK MISSING VALUES

In [11]:
missing_values = events.isnull().sum()

missing_summary = pd.DataFrame({
    "Missing Values": missing_values,
    "Missing Percentage": (
        missing_values / len(events) * 100
    ).round(2)
})

display(
    missing_summary.sort_values(
        by="Missing Percentage",
        ascending=False
    )
)

,Missing Values,Missing Percentage
No. Homeless,13152,83.63
No. Injured,11168,71.01
Magnitude,10598,67.39
"Total Damage, Adjusted (million US$)",10476,66.61
"Total Damage, Adjusted ('000 US$)",10476,66.61
No. Affected,5762,36.64
Total Deaths,4072,25.89
Total Affected,3361,21.37
Start Date,3185,20.25
Start Day,3185,20.25
End Date,3089,19.64
End Day,3089,19.64
End Month,552,3.51
Start Month,314,2.00
Event ID,0,0.00
Disaster Subgroup,0,0.00
Disaster Group,0,0.00
Start Year,0,0.00
Disaster Type,0,0.00
Country Impact Records,0,0.00
ISO Codes,0,0.00
Countries,0,0.00
Country Count,0,0.00
Decade,0,0.00
Classification Key,0,0.00
Disaster Subtype,0,0.00
End Year,0,0.00
No. Homeless Reported Country Impacts,0,0.00
No. Affected Reported Country Impacts,0,0.00
Total Deaths Reported Country Impacts,0,0.00
No. Injured Reported Country Impacts,0,0.00
"Total Damage, Adjusted ('000 US$) Reported Country Impacts",0,0.00
Total Affected Reported Country Impacts,0,0.00
"Total Damage, Adjusted (million US$) Reported Country Impacts",0,0.00
Magnitude Reported Country Impacts,0,0.00

In [12]:
events.info()

<class 'pandas.DataFrame'>
RangeIndex: 15727 entries, 0 to 15726
Data columns (total 35 columns):
 #   Column                                                         Non-Null Count  Dtype
---  ------                                                         --------------  -----
 0   Event ID                                                       15727 non-null  str
 1   Disaster Group                                                 15727 non-null  str
 2   Disaster Subgroup                                              15727 non-null  str
 3   Disaster Type                                                  15727 non-null  str
 4   Disaster Subtype                                               15727 non-null  str
 5   Classification Key                                             15727 non-null  str
 6   Start Year                                                     15727 non-null  int64
 7   Start Month                                                    15413 non-null  float64
 8   Start Day                                                      12542 non-null  float64
 9   Start Date                                                     12542 non-null  str
 10  End Year                                                       15727 non-null  int64
 11  End Month                                                      15175 non-null  float64
 12  End Day                                                        12638 non-null  float64
 13  End Date                                                       12638 non-null  str
 14  Decade                                                         15727 non-null  int64
 15  Country Count                                                  15727 non-null  int64
 16  Countries                                                      15727 non-null  str
 17  ISO Codes                                                      15727 non-null  str
 18  Country Impact Records                                         15727 non-null  int64
 19  Total Deaths                                                   11655 non-null  float64
 20  Total Deaths Reported Country Impacts                          15727 non-null  int64
 21  No. Injured                                                    4559 non-null   float64
 22  No. Injured Reported Country Impacts                           15727 non-null  int64
 23  No. Affected                                                   9965 non-null   float64
 24  No. Affected Reported Country Impacts                          15727 non-null  int64
 25  No. Homeless                                                   2575 non-null   float64
 26  No. Homeless Reported Country Impacts                          15727 non-null  int64
 27  Total Affected                                                 12366 non-null  float64
 28  Total Affected Reported Country Impacts                        15727 non-null  int64
 29  Total Damage, Adjusted ('000 US$)                              5251 non-null   float64
 30  Total Damage, Adjusted ('000 US$) Reported Country Impacts     15727 non-null  int64
 31  Total Damage, Adjusted (million US$)                           5251 non-null   float64
 32  Total Damage, Adjusted (million US$) Reported Country Impacts  15727 non-null  int64
 33  Magnitude                                                      5129 non-null   float64
 34  Magnitude Reported Country Impacts                             15727 non-null  int64
dtypes: float64(12), int64(13), str(10)
memory usage: 5.7 MB